//! The Claude Code setup system.
//!
//! One binary, two surfaces. The ai-stp provider commands are what the consumer
//! invokes; the human commands are what the owner types. Both reach the target
//! through `setup-core`, and neither has a shortcut around it.
//!
//! This file is the harness's *facts*. Every command over them lives in
//! [`harness_runtime`], shared with every other setup system, so a change to
//! behaviour lands once and a change to Claude Code's surface lands here.
//!
//! Claude Code installs itself, so this provider owns the configuration only.

use std::process::ExitCode;

mod software;

use harness_runtime::Harness;
use provider_v3::{ComponentKind, ProjectionKind};

/// Everything specific to Claude Code, verified against `claude-baseline.json`.
pub const CLAUDE: Harness = Harness {
    // The consumer's closed harness enum spells this `claude-code`, and that
    // enum is embedded in published corpus artifacts. Ours was not released, so
    // ours is the one that moves.
    harness_id: "claude-code",
    provider_id: "claude-setup-system",
    version: env!("CARGO_PKG_VERSION"),
    product: "Claude Code",
    vendor: "Anthropic",
    documented_config_home: "~/.claude",
    config_home_env: "CLAUDE_CONFIG_DIR",
    control_directory: ".claude-setup-system",
    state_file: "NDDEV-CLAUDE-PROVIDER.json",
    predecessor_state_file: "NDDEV-CLAUDE-SETUP.json",
    profile_id: "claude/native-and-marketplace/1",
    // Everything outside this list is a sibling overlay preserved verbatim.
    // Each entry is a surface `references/claude-baseline.json` sources. The
    // two that were here and are not documented are in that file's
    // `declined` list with the page that decided it: `.mcp.json`, because
    // Claude Code keeps MCP servers in `~/.claude.json` and nothing reads a
    // `.mcp.json` under this home; and `hooks`, because hooks are a key of
    // `settings.json` and `~/.claude/hooks/` is only where the scripts a
    // hook command names conventionally sit.
    native_namespaces: &["CLAUDE.md", "settings.json", "skills", "agents", "commands"],
    // The product's own. `plugins/` is the Claude CLI's registry and cache, not
    // ours to rewrite even though a setup can register a marketplace that fills
    // it; `projects/` is session history; `.credentials.json` is exactly what a
    // backup must never copy.
    never_touch: &[".credentials.json", "projects", "plugins"],
    // No near neighbour measured for this product. A marker listed here is a
    // refusal waiting to happen, so nothing is listed without evidence.
    foreign_homes: &[],
    permission_profiles: &["default"],
    // A plugin reaches Claude Code through `settings.json` -- `enabledPlugins`
    // and `extraKnownMarketplaces` -- rather than through a directory, which
    // is why `plugins` is disclaimed below and `Plugin` is declared here.
    //
    // `Mcp` and `Hook` were declared and are not: neither has a surface this
    // provider can own, so both were promises of a rollback nothing could
    // keep.
    component_kinds: &[
        ComponentKind::Instruction,
        ComponentKind::Skill,
        ComponentKind::Agent,
        ComponentKind::Command,
        ComponentKind::Plugin,
        ComponentKind::Setting,
    ],
    projection_kinds: &[
        ProjectionKind::NativeFiles,
        ProjectionKind::Marketplace,
        ProjectionKind::Plugin,
    ],
    // One scope. Claude Code keeps a project copy of every surface, but under `.claude/`
    // in the workspace rather than under this target -- a different root, not a
    // second scope of this one.
    //
    // Empty rather than absent: a harness that owns one target says so.
    scoped_projections: &[],
    max_files: 8192,
    max_bytes: 64 * 1024 * 1024,
    kit_identity: include_str!("../../../provider-kit/v3/KIT-IDENTITY.json"),
    // Generated by `build.rs` from this harness's `setups/` directory, so the
    // binary carries the catalog it is named after instead of hoping to find
    // one on a disk it was never shipped to.
    embedded_setups: include!(concat!(env!("OUT_DIR"), "/embedded_setups.rs")),
    software: Some(software::SOFTWARE),
};

fn main() -> ExitCode {
    harness_runtime::run(&CLAUDE, std::env::args().skip(1).collect())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::panic)]

    use super::*;

    /// The directory name this harness's setups live under in the workspace.
    const TOOL: &str = "claude";
    /// The declaration under test, named once so the shared test below reads
    /// the same in all seven crates.
    const HARNESS: Harness = CLAUDE;

    /// `build.rs` put the whole catalog in, under the paths it will be read by.
    ///
    /// This does **not** test for staleness, and an earlier version of this
    /// comment claimed it did. It cannot: `build.rs` declares
    /// `rerun-if-changed` on the catalog directory, so editing a setup rebuilds
    /// the table before this runs, and the test would be comparing the tree
    /// with itself. Observed — a deliberately edited setup left it green.
    ///
    /// What it does test is the build script, against a walk written
    /// independently of it: every file present, none invented, bytes exact, and
    /// paths relative and slash-separated. That last one is the one that would
    /// really break — `join("/")` is the only reason these keys are usable on
    /// Windows, and a path built with the platform separator would still look
    /// perfectly correct in the generated source.
    #[test]
    fn the_catalog_this_binary_carries_is_the_one_in_the_tree() {
        let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        // The workspace holds one directory per harness; a rendered public tree
        // ships one harness and holds it flat. Same two candidates `build.rs`
        // chooses between, asked the same way.
        let root = manifest.join("../../setups").join(TOOL);
        let root = if root.is_dir() {
            root
        } else {
            manifest.join("../../setups")
        };

        // Only the setup directories, which is what the reader lists and what
        // `build.rs` embeds. A rendered public tree also carries a
        // `setups/README.md` at the catalog root, which belongs to no setup.
        let mut on_disk = Vec::new();
        let mut stack: Vec<std::path::PathBuf> = std::fs::read_dir(&root)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .filter(|path| path.join("setup.json").is_file())
            .collect();
        while let Some(directory) = stack.pop() {
            for entry in std::fs::read_dir(&directory).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    stack.push(path);
                } else {
                    on_disk.push(path);
                }
            }
        }

        assert_eq!(
            HARNESS.embedded_setups.len(),
            on_disk.len(),
            "the binary carries {} files and the tree holds {}",
            HARNESS.embedded_setups.len(),
            on_disk.len()
        );

        for (relative, bytes) in HARNESS.embedded_setups {
            assert!(
                !relative.contains('\\') && !relative.starts_with('/'),
                "{relative:?} is not a relative slash path; a key built with the \
                 platform separator reads correctly on Unix and finds nothing on Windows"
            );
            let path = root.join(relative);
            let found = std::fs::read(&path)
                .unwrap_or_else(|e| panic!("{relative} is compiled in but not in the tree: {e}"));
            assert_eq!(
                &found, bytes,
                "{relative} differs between the binary and the tree"
            );
        }
    }

    fn baseline() -> serde_json::Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../references/claude-baseline.json");
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap()
    }

    #[test]
    fn the_config_home_and_environment_variable_match_the_verified_baseline() {
        let baseline = baseline();
        assert_eq!(baseline["config_dir"], CLAUDE.documented_config_home);
        assert_eq!(baseline["config_dir_env"], CLAUDE.config_home_env);
    }

    #[test]
    fn the_settings_file_the_baseline_names_is_one_we_own() {
        assert!(
            CLAUDE
                .native_namespaces
                .contains(&baseline()["settings_file"].as_str().unwrap())
        );
    }

    #[test]
    fn everything_the_baseline_marks_never_touch_is_disclaimed_here() {
        for entry in baseline()["never_touch"].as_array().unwrap() {
            let Some(name) = entry.as_str() else { continue };
            // `~/.claude.json` sits outside the target and cannot be a top-level
            // entry of it; the rest must be disclaimed by name.
            if name.starts_with('~') {
                continue;
            }
            assert!(
                !CLAUDE.native_namespaces.contains(&name),
                "{name} is marked never_touch by the baseline but claimed as ours"
            );
            assert!(
                CLAUDE.never_touch.contains(&name),
                "{name} is marked never_touch by the baseline but not disclaimed here"
            );
        }
    }

    #[test]
    fn the_cli_owned_plugin_registry_is_not_ours_to_rewrite() {
        // The baseline lists these under `cli_owned`. A setup may register a
        // marketplace that causes the CLI to fill them; writing them directly
        // would be writing the product's own bookkeeping.
        for entry in baseline()["cli_owned"].as_array().unwrap() {
            let name = entry.as_str().unwrap();
            let top = name.split('/').next().unwrap();
            assert!(
                !CLAUDE.native_namespaces.contains(&top),
                "{top} is CLI-owned but claimed"
            );
        }
    }

    #[test]
    fn the_declaration_is_valid_and_names_this_host() {
        let info = CLAUDE.provider_info().unwrap();
        assert_eq!(info.provider_id, env!("CARGO_PKG_NAME"));
        assert_eq!(info.protocol_version, 3);
        assert!(info.supports_this_host());
    }

    #[test]
    fn no_namespace_is_both_owned_and_disclaimed() {
        for name in CLAUDE.never_touch {
            assert!(
                !CLAUDE.native_namespaces.contains(name),
                "{name} is claimed and disclaimed"
            );
        }
    }
    /// Everything this harness claims to own, against the vendor page that
    /// decided it.
    ///
    /// What this replaced only checked that the baseline parsed. The block it
    /// reads now is hand-authored beside the rest of the baseline, and this is
    /// what keeps that block from being decoration: a namespace no vendor
    /// document names, or a declared kind no owned surface routes, is red here.
    ///
    /// Both directions, because the defect it was written for ran both ways --
    /// `~/.cursor/rules` was owned and does not exist, `~/.pi/agent/prompts`
    /// exists and was not owned. Conformance caught neither: its
    /// `declared_native_route_is_compilable` case asks for **one** route, not
    /// every one.
    #[test]
    fn every_surface_this_harness_owns_is_one_the_vendor_documents() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../references")
            .join(format!("{TOOL}-baseline.json"));
        let baseline: serde_json::Value =
            serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
        let problems = harness_runtime::surfaces::disagreements(&HARNESS, &baseline);
        assert!(
            problems.is_empty(),
            "the declaration and {TOOL}-baseline.json disagree:\n  {}",
            problems.join("\n  ")
        );
    }
    /// A setup that writes a configuration file says where its format came from.
    ///
    /// The release before this one made the *surfaces* sourced: a path this
    /// provider owns cites the page that documents it. This is the same rule
    /// one level down, and it was written because two of the seven failed it.
    ///
    /// opencode's baseline set `"permission": "ask"` where the product
    /// documents an object of tool names, and antigravity's set
    /// `toolPermissions` where the product reads `toolPermission` with four
    /// values, none of them the one written. Both were valid JSON in the right
    /// file at the right path. Both installed, verified and restored cleanly.
    /// Neither changed anything about the product — a target that looks
    /// configured and is not, which is the failure this estate refuses one
    /// level up and had been shipping one level down.
    #[test]
    fn a_setup_that_writes_configuration_says_where_its_format_came_from() {
        let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let root = manifest.join("../../setups").join(TOOL);
        let root = if root.is_dir() {
            root
        } else {
            manifest.join("../../setups")
        };
        let catalog = harness_runtime::Catalog::at(&root);
        let problems = harness_runtime::catalog::unsourced(&catalog.list().unwrap());
        assert!(problems.is_empty(), "{}", problems.join("\n  "));
    }
    /// Three postures, on every one of the seven.
    ///
    /// `baseline` is a working floor, `minimal` is the product's own defaults,
    /// and `full-auto` asks nothing and sandboxes nothing. A caller who learns
    /// them on one product knows them on all seven, which is the whole reason
    /// the names are the estate's rather than each harness's.
    ///
    /// The second half of the check is the one worth having: two setups with
    /// the same bytes mean one of them is a posture in name only, and it would
    /// still read as offered in `list`.
    #[test]
    fn the_three_postures_are_offered_and_are_actually_different() {
        let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let root = manifest.join("../../setups").join(TOOL);
        let root = if root.is_dir() {
            root
        } else {
            manifest.join("../../setups")
        };
        let catalog = harness_runtime::Catalog::at(&root);
        let problems = harness_runtime::catalog::asymmetric(&catalog.list().unwrap());
        assert!(problems.is_empty(), "{}", problems.join("\n  "));
    }
}
